### ISSUE TITLE
请问train img要怎么创建？

### ISSUE THREAD

**Issue by wzshuang** [isee15/captcha-ocr#1]
是要手动创建好吗？

**Comment by isee15** [comment]
如果是非常简单的，可以手动创建。
通用一点的方式是用程序创建，找一张图片a.jpg，肉眼识别一下里面的内容，文件名改成肉眼识别的字母7A2B.png等。然后对这张图片按照识别过程分割成4张图，分别把这4张图命名成7.png,A.png,2.png,B.png等。
pwntcha里面用了另外的方式，直接判断图片用了什么字体，然后直接用对应字体把字母内容画出来。

**Comment by wzshuang** [comment]
多谢，这个项目很赞，已加星星
